package pageUIs.categories;

public class CheckoutPageUI {
    public static final String SAME_ADDRESS_CHECKBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='ShipToSameAddress']";
    public static final String BILLING_FIRST_NAME_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_FirstName']";
    public static final String BILLING_LAST_NAME_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_LastName']";
    public static final String BILLING_EMAIL_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_Email']";
    public static final String COUNTRY_DROPDOWN = "xpath=//div[@id='checkout-billing-load']//select[@id='BillingNewAddress_CountryId']";
    public static final String STATE_PROVINCE_DROPDOWN = "xpath=//div[@id='checkout-billing-load']//select[@id='BillingNewAddress_StateProvinceId']";
    public static final String BILLING_CITY_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_City']";
    public static final String BILLING_ADDRESS1_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_Address1']";
    public static final String BILLING_ZIP_POSTAL_CODE_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_ZipPostalCode']";
    public static final String BILLING_PHONE_NUMBER_TEXTBOX = "xpath=//div[@id='checkout-billing-load']//input[@id='BillingNewAddress_PhoneNumber']";
    public static final String CONTINUE_BUTTON_BILLING_ADDRESS = "xpath=//div[@id='checkout-step-billing']//button[text()='Continue']";
    public static final String CONTINUE_BUTTON_SHIPPING_METHOD = "xpath=//div[@id='checkout-step-shipping-method']//button[text()='Continue']";
    public static final String CONTINUE_BUTTON_PAYMENT_METHOD = "xpath=//div[@id='checkout-step-payment-method']//button[text()='Continue']";
    public static final String CONTINUE_BUTTON_PAYMENT_INFORMATION = "xpath=//div[@id='checkout-step-payment-info']//button[text()='Continue']";
    public static final String CONTINUE_BUTTON_SHIPPING_ADDRESS = "xpath=//div[@id='shipping-buttons-container']//button[text()='Continue']";
    public static final String LOADING_NEXT_STEP = "xpath=//span[@class='please-wait']";
    public static final String ADDRESS_DROPDOWN = "xpath=//div[@id='shipping-addresses-form']//select[@id='shipping-address-select']";
    public static final String SHIPPING_FIRST_NAME_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_FirstName']";
    public static final String SHIPPING_LAST_NAME_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_LastName']" ;
    public static final String SHIPPING_EMAIL_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_Email']";
    public static final String SHIPPING_CITY_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_City']";
    public static final String SHIPPING_ADDRESS1_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_Address1']";
    public static final String SHIPPING_ZIP_POSTAL_CODE_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_ZipPostalCode']";
    public static final String SHIPPING_PHONE_NUMBER_TEXTBOX = "xpath=//div[@id='shipping-new-address-form']//input[@id='ShippingNewAddress_PhoneNumber']";
    public static final String SHIPPING_COUNTRY_DROPDOWN = "xpath=//div[@id='shipping-new-address-form']//select[@id='ShippingNewAddress_CountryId']";
    public static final String SHIPPING_STATE_PROVINCE_DROPDOWN = "xpath=//div[@id='shipping-new-address-form']//select[@id='ShippingNewAddress_StateProvinceId']";
    public static final String SHIPPING_METHOD_RADIOBUTTON = "xpath=//div[@id='shipping-methods-form']//label[text()='%s']/preceding-sibling::input";
    public static final String PAYMENT_METHOD_RADIOBUTTON = "xpath=//div[@class='section payment-method']//label[text()=\"%s\"]/preceding-sibling::input";
    public static final String CONFIRM_BILLING_FIRSTNAME_LASTNAME = "xpath=//div[@class='billing-info']//li[@class='name']";
    public static final String CONFIRM_BILLING_EMAIL = "xpath=//div[@class='billing-info']//li[@class='email']";
    public static final String CONFIRM_BILLING_PHONE_NUMBER = "xpath=//div[@class='billing-info']//li[@class='phone']";
    public static final String CONFIRM_BILLING_COUNTRY = "xpath=//div[@class='billing-info']//li[@class='country']";
    public static final String CONFIRM_BILLING_PROVINCE_STATE = "xpath=//div[@class='billing-info']//li[@class='stateprovince']";
    public static final String CONFIRM_BILLING_CITY = "xpath=//div[@class='billing-info']//li[@class='city']";
    public static final String CONFIRM_BILLING_ADDRESS1 = "xpath=//div[@class='billing-info']//li[@class='address1']";
    public static final String CONFIRM_BILLING_ZIP_POSTAL_CODE = "xpath=//div[@class='billing-info']//li[@class='zippostalcode']";
    public static final String CONFIRM_BILLING_PAYMENT_METHOD = "xpath=//div[@class='payment-method-info']//li[@class='payment-method']/span[@class='value']";
    public static final String CONFIRM_SHIPPING_FIRSTNAME_LASTNAME = "xpath=//div[@class='shipping-info-wrap']//li[@class='name']";
    public static final String CONFIRM_SHIPPING_EMAIL = "xpath=//div[@class='shipping-info-wrap']//li[@class='email']";
    public static final String CONFIRM_SHIPPING_PHONE = "xpath=//div[@class='shipping-info-wrap']//li[@class='phone']";
    public static final String CONFIRM_SHIPPING_COUNTRY = "xpath=//div[@class='shipping-info-wrap']//li[@class='country']";
    public static final String CONFIRM_SHIPPING_PROVINCE_STATE = "xpath=//div[@class='shipping-info-wrap']//li[@class='stateprovince']";
    public static final String CONFIRM_SHIPPING_CITY = "xpath=//div[@class='shipping-info-wrap']//li[@class='city']";
    public static final String CONFIRM_SHIPPING_ADDRESS1 = "xpath=//div[@class='shipping-info-wrap']//li[@class='address1']";
    public static final String CONFIRM_SHIPPING_ZIP_POSTAL_CODE = "xpath=//div[@class='shipping-info-wrap']//li[@class='zippostalcode']";
    public static final String CONFIRM_SHIPPING_METHOD = "xpath=//div[@class='shipping-method-info']//li[@class='shipping-method']//span[@class='value']";
    public static final String PRODUCT_SKU_BY_PRODUCT_NAME = "xpath=//table[@class='cart']//a[text()='%s']/parent::td[@class='product']/preceding-sibling::td[@class='sku']";
    public static final String PRODUCT_NAME_IN_CART_TABLE = "xpath=//td[@class='product']/a[@class='product-name']";
    public static final String PRODUCT_PRICE_BY_PRODUCT_NAME = "xpath=//table[@class='cart']//a[text()='%s']/parent::td/following-sibling::td[@class='unit-price']/span";
    public static final String PRODUCT_TOTAL_PRICE_BY_PRODUCT_NAME = "xpath=//table[@class='cart']//a[text()='%s']/parent::td[@class='product']/following-sibling::td[@class='subtotal']/span";
    public static final String SUB_TOTAL_PRICE_IN_TOTAL_INFO = "xpath=//div[@class='total-info']//tr[@class='order-subtotal']//span";
    public static final String TOTAL_PRICE_IN_TOTAL_INFO = "xpath=//div[@class='total-info']//tr[@class='order-total']//span";
    public static final String CONFIRM_BUTTON = "xpath=//div[@id='confirm-order-buttons-container']//button";
    public static final String THANK_YOU_TITLE = "xpath=//div[@class='page checkout-page order-completed-page']/div[@class='page-title']";
    public static final String ORDER_SUCCESSFULLY_MESSAGE = "xpath=//div[@class='page checkout-page order-completed-page']//div[@class='section order-completed']/div[@class='title']";
    public static final String ORDER_NUMBER = "xpath=//div[@class='page checkout-page order-completed-page']//div[@class='order-number']";
}
